dist: trusty
language: python
group: edge

python:
  - "3.6"
services:
  - docker

addons:
  apt:
    packages:
      - docker-ce

env:
  global:
    - SERVICE0="conda"
    - SERVICE1="keras-tf"

  matrix:
    - PYTHON_MAJOR="2" ARCH_TAG="amd64"
    - PYTHON_MAJOR="3" ARCH_TAG="amd64"
    - PYTHON_MAJOR="2" ARCH_TAG="arm32v7"
    - PYTHON_MAJOR="3" ARCH_TAG="arm32v7"
    - PYTHON_MAJOR="3" ARCH_TAG="arm64v8"

before_install:

  # Put docker into "experimental" for manifest function
  - mkdir -p $HOME/.docker
  - echo '{"experimental":"enabled"}' > "$HOME/.docker/config.json"

  - pip3 install pyyaml  # for manifest-it

    # Register qemu as cross-compiler
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset

install:

  # Build image
  - docker-compose build $SERVICE0-py$PYTHON_MAJOR-$ARCH_TAG $SERVICE1-py$PYTHON_MAJOR-$ARCH_TAG

script: true

after_success:

  # Login to docker for push
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

  # manifest and push
  - python3 manifest-it.py conda-xarch.manifest.yml

