- image: "derekmerck/conda:py2"

  manifests:
    - image: "derekmerck/conda:py2-amd64"
      platform:
        architecture: amd64
        os: linux

    - image: "derekmerck/conda:py2-arm32v7"
      platform:
        architecture: arm
        variant: v7
        os: linux

- image: "derekmerck/conda:latest"

  manifests:
    - image: "derekmerck/conda:py3-amd64"
      platform:
        architecture: amd64
        os: linux

    - image: "derekmerck/conda:py3-arm32v7"
      platform:
        architecture: arm
        variant: v7
        os: linux

    - image: "derekmerck/conda:py3-arm64v8"
      platform:
        architecture: arm
        variant: v7
        os: linux

- image: "derekmerck/conda:py2-tfk"

  manifests:
    - image: "derekmerck/conda:py2-tf190-k222-amd64"
      platform:
        architecture: amd64
        os: linux

    - image: "derekmerck/conda:py2-tf190-k222-arm32v7"
      platform:
        architecture: arm
        variant: v7
        os: linux

- image: "derekmerck/conda:py3-tfk"

  manifests:
    - image: "derekmerck/conda:py3-tf190-k222-amd64"
      platform:
        architecture: amd64
        os: linux

    - image: "derekmerck/conda:py3-tf190-k222-arm32v7"
      platform:
        architecture: arm
        variant: v7
        os: linux

    - image: "derekmerck/conda:py3-tf190-k222-arm64v8"
      platform:
        architecture: arm
        variant: v8
        os: linux
