# xArch Keras Image
# Derek Merck, Summer 2018

ARG PYTHON_MAJOR=3
ARG ARCH="amd64"

FROM derekmerck/conda:py${PYTHON_MAJOR}-${ARCH}
MAINTAINER Derek Merck <derek_merck@brown.edu>

ARG PYTHON_MAJOR=3
ARG TF_WHL_URL=https://storage.googleapis.com/tensorflow/linux/cpu/
ARG TF_WHL_FILE=tensorflow-1.9.0rc0-cp34-cp34m-linux_x86_64.whl

RUN apt-get update && apt-get install -yq --no-install-recommends \
        build-essential \
        gfortran \
        libatlas-base-dev \
        libopenblas-dev \
#        python3-openssl \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

RUN echo "source activate base" >> ~/.bashrc \
    && conda install -y numpy scipy hdf5 pyyaml pillow pyopenssl \
    && pip install --no-deps parameterized pydicom ruamel.yaml pydot \
    && curl -L -o tensorflow-1.9-py"${PYTHON_MAJOR}"-none-any.whl ${TF_WHL_URL}${TF_WHL_FILE} \
    && pip install --no-deps tensorflow-1.9-py"${PYTHON_MAJOR}"-none-any.whl \
    && rm tensorflow-1.9-py"${PYTHON_MAJOR}"-none-any.whl

ENV KERAS_BACKEND=tensorflow

RUN pip install keras
